server:
  port: 8003

spring:
  application:
    name: service-hi
  cloud:
    inetutils:
      default-ip-address: 192.168.0.104

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.inetutils.default-ip-address}:${server.port}





